# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LiamUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LiamUi(object):
    def setupUi(self, LiamUi):
        LiamUi.setObjectName("LiamUi")
        LiamUi.resize(911, 671)
        self.centralwidget = QtWidgets.QWidget(LiamUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 921, 671))
        self.label.setStyleSheet("background:transparent;\n"
                                 "border-radius:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Main.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(-10, 560, 291, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("LIAM.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 331, 225))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("loading.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 610, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 610, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 10, 271, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background:transparent;\n"
                                   "border-radius:none;\n"
                                   "font: 20px \"MS Shell Dlg 2\";\n"
                                   "color:white;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        LiamUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(LiamUi)
        QtCore.QMetaObject.connectSlotsByName(LiamUi)

    def retranslateUi(self, LiamUi):
        _translate = QtCore.QCoreApplication.translate
        LiamUi.setWindowTitle(_translate("LiamUi", "MainWindow"))
        self.pushButton.setText(_translate("LiamUi", "START"))
        self.pushButton_2.setText(_translate("LiamUi", "STOP"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LiamUi = QtWidgets.QMainWindow()
    ui = Ui_LiamUi()
    ui.setupUi(LiamUi)
    LiamUi.show()
    sys.exit(app.exec_())
